epoch: 1000
evalFreq: 1
testFreq: 10
gpus: 4
vRam: -1
wantsMore: false
dataset: compression
repeat: 1 # duplicate images in one epoch
valDataset: clic/valid
batchSize: 10
model:
    type: Big
    target: ssim
    channel: 128
    k: [8192, 2048, 512]
    m: 2
    withGroup: false
    withAtt: true
    withDropout: false
    alias: false
    ema: -1.0
optim:
    type: Lamb
    params:
        lr: 2.5e-3
        weight_decay: 0.0
        use_nvlamb: true
schdr:
    type: CosineWarmRestart
    params:
        first_cycle_steps: 500 # match 10 * testFreq
        warmup_steps: 50
        gamma: 0.1
tempSchdr:
    type: CosineWithEnd
    params:
        maxValue: 1.0
        minValue: 0.01
        totalStep: 1050
regSchdr:
    type: MultiStep
    params:
        initValue: 1.
        gamma: 1.0
        stepInterval: 1
# regSchdr:
#     type: Jump
#     params:
#         initValue: 0.5
#         minValue: 1.e-20
#         gamma: 0.99 # 10.0 * (gamma ^ 500) = 0.01
#         stepInterval: 1
# regSchdr:
#     type: JumpAlter
#     params:
#         initValue: 1.0
#         minValue: 0.00000001
#         gamma: 0.6683439175686146 # 1.0 * (gamma ^ 30) = 1.e-7
#         stepInterval: 1
#         milestone: 600
#         valueAfterMilestone: 1.e-6
warmStart: ""
method: New
