name: mcquic
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python>=3.9
  - conda
  - pip
  - pytorch<2
  - torchvision<1
  - cudatoolkit
  - tensorboard<3
  - rich<11
  - scipy<2
  - python-lmdb<2
  - pyyaml<7
  - marshmallow<4
  - click<9
  - pip:
    - vlutils
