name: mcqc
channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - cudatoolkit
  - tensorboard
  - tqdm
  - scipy
  - matplotlib
  - pip:
    - pyyaml
    - vlutils
    - lmdb
    # need gcc > 8, nvcc
    - compressai
