name: pytorch
channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia
dependencies:
  - python
  - pip
  - pytorch>1.9
  - torchvision
  - cudatoolkit
  - numpy
  - scipy
  - tensorboard
  - tqdm
  - pynvml
  - pip:
    - pyyaml
    - opencv-python
    - cfmUtils
    - pyro-ppl
    - storchastic
    - lmdb
    # need gcc > 8, nvcc
    - compressai
    - packaging
