name: mcquic
channels:
  - pytorch
  - defaults
  - conda-forge
  - xiaosu-zhu
dependencies:
  - python>=3.9
  - conda
  - pip
  - tensorboard<3
  - rich<11
  - scipy<2
  - python-lmdb<2
  - pyyaml<7
  - marshmallow<4
  - click<9
  - tqdm
  - vlutils
  - pybind11
