{% set data = load_setup_py_data() %}

package:
  name: mcquic
  version: {{ data.get('version') }}

source:
  - path: ../mcquic
    folder: mcquic
  - path: ../third_party
    folder: third_party
  - path: ../setup.py
  - path: ../setup.cfg

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - pybind11
    - pytorch<2
    - pip

  run:
    - python>=3.9
    - pytorch<2
    - torchvision<1
    - tqdm
    - tensorboard<3
    - rich<11
    - python-lmdb<2
    - pyyaml<7
    - marshmallow<4
    - click<9
    - vlutils
    - msgpack-python<2

# Write it by finalize.py
build:
  entry_points:
    ${{ ENTRY_POINTS }}
  include_recipe: False

about:
  home: https://github.com/xiaosu-zhu/McQuic
  license: Apache-2.0
  summary: McQuic, a.k.a. Multi-codebook Quantizers for neural image compression
