{% set data = load_setup_py_data() %}

package:
  name: mcquic
  version: {{ data.get('version') }}

source:
  - path: ../mcquic
    folder: mcquic
  - path: ../third_party
    folder: third_party
  - path: ../setup.py
  - path: ../setup.cfg

requirements:
  build:
    - {{ compiler('cxx') }}
    # cross-compile from https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
  host:
    - python>=3.9
    - setuptools
    - pybind11
    - pip
    - pytorch<2

  run:
    - python>=3.9
    - pytorch<2
    - torchvision<1
    - tqdm
    - tensorboard<3
    - rich<11
    - python-lmdb<2
    - pyyaml<7
    - marshmallow<4
    - click<9
    - vlutils
    - msgpack-python<2
    - packaging

# Write it by finalize.py
build:
  entry_points:
    - mcquic = mcquic.cli:entryPoint
    - mcquic-train = mcquic.train.cli:entryPoint
    - mcquic-dataset = mcquic.datasets.cli:entryPoint
    - mcquic-validate = mcquic.validate.cli:entryPoint
  include_recipe: False

about:
  home: https://github.com/xiaosu-zhu/McQuic
  license: Apache-2.0
  summary: McQuic, a.k.a. Multi-codebook Quantizers for neural image compression
