model:
    type: Compressor
    params:
        channel: 128
        k: [8192, 2048, 512]
        m: 2
optim:
    type: Lamb
    params:
        lr: 1.e-3
        # weight_decay: 0.0
        # use_nvlamb: true
schdr:
    type: CosineAnnealingWarmupRestarts
    params:
        first_cycle_steps: 1000 # match 10 * testFreq
        warmup_steps: 5
        gamma: 0.9
training:
    batchSize: 8
    epoch: 1000
    valFreq: 10
    trainSet: data/compression
    valSet: data/clic/valid
    saveDir: saved
    target: MsSSIM
gpu:
    gpus: 4
    vRam: 20000
    wantsMore: false
