epoch: 10000000000
evalFreq: 2
testFreq: 20
gpus: 3
vRam: -1
wantsMore: false
dataset: fullDataset
repeat: 1 # duplicate images in one epoch
valDataset: clic/valid
batchSize: 4
model:
    type: Big
    target: ssim
    channel: 192
    k: [8192, 2048, 512]
    m: 4
    withGroup: false
    withAtt: true
    withDropout: false
    alias: false
    ema: -1.0
optim:
    type: Lamb
    params:
        lr: 4.e-4
        # weight_decay: 0.0
        # use_nvlamb: true
# schdr:
#     type: MultiStepWarmUp
#     params:
#         milestones: [100, 800, 900] # manually divided by repeat
#         gamma: 0.1
schdr:
    type: CosineWarmRestart
    params:
        first_cycle_steps: 200 # match 10 * testFreq
        warmup_steps: 40
        gamma: 0.9
# regSchdr:
#     type: Cyclic
#     params:
#         initValue: 0.0001
#         gamma: 1.0
#         cyclicInterval: 100
#         boostInterval: 2
#         zeroOutRatio: 0.3
regSchdr:
    type: MultiStep
    params:
        initValue: 0.0
        gamma: 1.e-3
        stepInterval: 600 # manually divided by repeat
# regSchdr:
#     type: Jump
#     params:
#         initValue: 0.5
#         minValue: 1.e-20
#         gamma: 0.99 # 10.0 * (gamma ^ 500) = 0.01
#         stepInterval: 1
# regSchdr:
#     type: JumpAlter
#     params:
#         initValue: 1.0
#         minValue: 0.00000001
#         gamma: 0.6683439175686146 # 1.0 * (gamma ^ 30) = 1.e-7
#         stepInterval: 1
#         milestone: 600
#         valueAfterMilestone: 1.e-6
warmStart: "" # ckpt/3-14+12+10.ckpt
method: New
