epoch: 10000000000
evalStep: 5000
testStep: 50000
gpus: 4
vRam: -1
wantsMore: false
dataset: compression
valDataset: clic/valid
batchSize: 8
coef:
    ssim: 1.0
    l1l2: 0.0
model:
    type: Base
    channel: 256
    k: 256
    m: 4
    withGroup: true
    withAtt: true
    withDropout: false
    alias: true
    ema: -1.0
optim:
    type: Adam
    params:
        lr: 5.e-6
schdr:
    type: MultiStepWarmUp
    params:
        milestones: [50, 2000, 4000, 8000]
        gamma: 0.5
regSchdr:
    type: Cyclic
    params:
        initValue: 0.01
        gamma: 1.0
        cyclicInterval: 100
        boostInterval: 3
        zeroOutRatio: 0.5
# regSchdr:
#     type: MultiStep
#     params:
#         initValue: 0.01
#         gamma: 0.5
#         stepInterval: 2000
warmStart: "" # ckpt/aq.ckpt
method: Plain
