epoch: 10000000000
evalStep: 5000
testStep: 50000
gpus: 4
vRam: -1
wantsMore: false
dataset: fullDataset1
valDataset: clic/valid
batchSize: 8
coef:
    ssim: 1.0
    l1l2: 0.0
model:
    type: Base
    channel: 256
    k: 256
    m: 4
    withGroup: true
    withAtt: true
    withDropout: false
    alias: true
optim:
    type: Adam
    params:
        lr: 4.e-5
schdr:
    type: MultiStep
    params:
        milestones: [400, 800, 1200]
        gamma: 0.5
# regSchdr:
#     type: Cyclic
#     params:
#         initValue: 0.1
#         gamma: 1.0
#         cyclicInterval: 10
#         boostInterval: 3
#         zeroOutRatio: 0.9999
regSchdr:
    type: MultiStep
    params:
        initValue: 0.02
        gamma: 0.1
        stepInterval: 200
warmStart: ""
method: Plain
