epoch: 10000000000
evalStep: 500
testStep: 5000
gpus: 4
vRam: -1
wantsMore: false
dataset: compression
repeat: 10 # duplicate images in one epoch
valDataset: clic/valid
batchSize: 9
coef:
    ssim: 1.0
    l1l2: 0.0
model:
    type: Big
    channel: 192
    k: [4096, 1024, 256]
    m: 3
    withGroup: true
    withAtt: true
    withDropout: false
    alias: true
    ema: -1.0
optim:
    type: Adam
    params:
        lr: 7.e-6
schdr:
    type: MultiStepWarmUp
    params:
        milestones: [50, 800, 1600] # manually divided by repeat
        gamma: 0.1
# regSchdr:
#     type: Cyclic
#     params:
#         initValue: 0.0001
#         gamma: 1.0
#         cyclicInterval: 100
#         boostInterval: 2
#         zeroOutRatio: 0.3
regSchdr:
    type: MultiStep
    params:
        initValue: 0.0
        gamma: 1.e-3
        stepInterval: 600 # manually divided by repeat
# regSchdr:
#     type: Jump
#     params:
#         initValue: 0.5
#         minValue: 1.e-20
#         gamma: 0.99 # 10.0 * (gamma ^ 500) = 0.01
#         stepInterval: 1
# regSchdr:
#     type: JumpAlter
#     params:
#         initValue: 1.0
#         minValue: 0.00000001
#         gamma: 0.6683439175686146 # 1.0 * (gamma ^ 30) = 1.e-7
#         stepInterval: 1
#         milestone: 600
#         valueAfterMilestone: 1.e-6
warmStart: "" # ckpt/big.ckpt
method: New
