epoch: 10000000000
evalStep: 5000
testStep: 50000
gpus: 4
vRam: -1
wantsMore: false
dataset: compression
valDataset: clic/valid
batchSize: 9
coef:
    ssim: 1.0
    l1l2: 0.0
model:
    type: Base
    channel: 192
    k: 4096
    m: 3
    withGroup: true
    withAtt: true
    withDropout: false
    alias: true
    ema: -1.0
optim:
    type: Adam
    params:
        lr: 7.e-6
schdr:
    type: MultiStepWarmUp
    params:
        milestones: [100, 2000, 4000]
        gamma: 0.1
# regSchdr:
#     type: Cyclic
#     params:
#         initValue: 0.0001
#         gamma: 1.0
#         cyclicInterval: 100
#         boostInterval: 2
#         zeroOutRatio: 0.3
# regSchdr:
#     type: MultiStep
#     params:
#         initValue: 0.0
#         gamma: 0.1
#         stepInterval: 1000
regSchdr:
    type: Jump
    params:
        initValue: 0.1
        minValue: 0.0000001
        gamma: 0.954992586021436 # 10.0 * (gamma ^ 500) = 0.01
        stepInterval: 1
warmStart: ckpt/newPQ.ckpt
method: Plain
