epoch: 10000000000
evalStep: 5000
testStep: 50000
gpus: 4
vRam: -1
wantsMore: false
dataset: compression
valDataset: clic/valid
batchSize: 8
coef:
    ssim: 1.0
    l1l2: 0.0
    reg: 1.e-4
    gen: 0.0
    dis: 0.0
model:
    type: Base
    channel: 256
    k: 256
    m: 4
    withGroup: true
    withAtt: true
    withDropout: true
    alias: true
optim:
    type: Adam
    params: {}
        # lr: 2.e-6
        # weight_decay: 1.e-5
schdr:
    type: Cyclic
    params:
         base_lr: 1.e-7
         max_lr: 1.e-4
         step_size_up: 200
         mode: exp_range
         gamma: 0.9999
        # max_lr: 1.e-4
        # epochs: 2000
        # steps_per_epoch: 43
        # three_phase: true
warmStart: "" # "ckpt/32bit.ckpt"
method: Plain
