epoch: 10000000000
evalStep: 500
testStep: 5000
gpus: 4
vRam: -1
wantsMore: false
dataset: fullDataset
repeat: 1 # duplicate images in one epoch
valDataset: clic/valid
batchSize: 6
model:
    type: Big
    channel: 192
    k: [8192, 2048, 512] # 12 * (14 / 256 + 12 / 1024 + 10 / 4096) = 0.826171875
    m: 8 
    withGroup: false
    withAtt: true
    target: psnr
    alias: false
    ema: -1.0
optim:
    type: Adam
    params:
        lr: 2.e-5
schdr:
    type: MultiStepWarmUp
    params:
        milestones: [10, 200, 300] # manually divided by repeat
        gamma: 0.1
# regSchdr:
#     type: Cyclic
#     params:
#         initValue: 0.0001
#         gamma: 1.0
#         cyclicInterval: 100
#         boostInterval: 2
#         zeroOutRatio: 0.3
regSchdr:
    type: MultiStep
    params:
        initValue: 0.0
        gamma: 1.e-3
        stepInterval: 600 # manually divided by repeat
# regSchdr:
#     type: Jump
#     params:
#         initValue: 0.5
#         minValue: 1.e-20
#         gamma: 0.99 # 10.0 * (gamma ^ 500) = 0.01
#         stepInterval: 1
# regSchdr:
#     type: JumpAlter
#     params:
#         initValue: 1.0
#         minValue: 0.00000001
#         gamma: 0.6683439175686146 # 1.0 * (gamma ^ 30) = 1.e-7
#         stepInterval: 1
#         milestone: 600
#         valueAfterMilestone: 1.e-6
warmStart: "" # ckpt/newPQ.ckpt
method: New
