version: v1.0

encoder:
  - ResidualBlockWithStride(`channel`, `hidden`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlockWithStride(`channel`, `hidden`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlockWithStride(`channel`, `hidden`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)


quantizer:
  - QuantizerEncoder(`channel`, `level`, `m`, `k`)
  - QuantizerDecoder(`channel`, `level`, `m`, `k`)


decoder:
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlockShuffle(`channel`, `channel`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlockShuffle(`channel`, `channel`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlock(`channel`, `channel`, groups=`m`)
  - ResidualBlockShuffle(`channel`, `channel`, groups=`m`)
  - Conv2D(`channel`, 3)
