epoch: 10000000000
gpus: 4
vRam: -1
wantsMore: false
dataset: clic/train
valDataset: clic/valid
batchSize: 2
lr: 1.e-5
coef:
    ssim: 1.0
    l1l2: 1.0
    reg: 1.0
    gen: 1.0
    dis: 0.0
model:
    type: pq
    channel: 512
    k: [256, 256, 256, 256, 256, 256, 256, 256]
    numLayers: 1
