epoch: 10000000000
gpus: 4
vRam: -1
wantsMore: false
dataset: clic/train
valDataset: clic/valid
batchSize: 12
lr: 1.e-5
coef:
    ssim: 1.0
    l1l2: 1.0
    reg: 0.0
    gen: 1.0
    dis: 0.0
model:
    type: pq
    channel: 512
    k: [2048, 2048, 2048, 2048, 2048, 2048, 2048, 2048]
    numLayers: 6
