epoch: 10000000000
evalStep: 5000
testStep: 50000
gpus: 4
vRam: -1
wantsMore: false
dataset: compression1
valDataset: clic/test
batchSize: 8
coef:
    ssim: 1.0
    l1l2: 0.0
    reg: 0.0
    gen: 0.0
    dis: 0.0
model:
    type: Base
    channel: 256
    k: 256
    m: 32
    withAtt: true
    withDropout: false
    alias: false
optim:
    type: Adam
    params:
        lr: 5.e-6
schdr:
    type: MultiStep
    params:
        milestones: [50, 100, 200]
        gamma: 0.25
warmStart: ckpt/global.ckpt
method: FineTune
