epoch: 10000000000
gpus: 4
vRam: -1
wantsMore: false
dataset: clic/train
valDataset: clic/valid
batchSize: 8
lr: 5.e-5
coef:
    ssim: 1.0
    l1l2: 1.0
    reg: 0.0
    gen: 0.0
    dis: 0.0
model:
    type: Base
    channel: 256
    k: 256
    m: 32
    numLayers: 1
method: Plain
