name: Update schema.json and docs based on mcquic.config.ConfigSchema

on:
  push:
    branches: [main]
    paths: ['mcquic/config.py']

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Generate schema.json
        run: |
          pip install marshmallow-jsonschema apispec json-schema-for-humans
          python ci/generate_schema.py mcquic/config.py configs/schema.json configs/README.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update config schema and configs/README.md
