name: Auto generate stub of RANS cpp module

on:
  push:
    branches: [main]
    paths: ['third_party/CompressAI/**']

jobs:
  update-stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Add dependencies
        run: |
          pip install pybind11 pybind11-stubgen
          NPY_NUM_BUILD_JOBS=8 pip install -e .
      - name: Generate python stubs
        run: |
          pybind11-stubgen --no-setup-py mcquic.rans
          mv stubs/mcquic/rans-stubs/*.pyi mcquic/rans.pyi
          sed -i 's/: str/: bytes/g' mcquic/rans.pyi
          rm -rf stubs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update config schema and configs/README.md
