name: Auto generate stub of RANS cpp module

on:
  push:
    branches: [main]
    paths: ['third_party/CompressAI/**']

jobs:
  update-stub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: Install dependencies
        run: |
          ./install.sh
          eval "$(conda shell.bash hook)"
          conda activate
          conda install -y pip
          pip install pybind11 pybind11-stubgen
      - name: Generate python stubs
        run: |
          eval "$(conda shell.bash hook)"
          conda activate
          pybind11-stubgen --no-setup-py mcquic.rans
          mv stubs/mcquic/rans-stubs/*.pyi mcquic/rans.pyi
          sed -i 's/: str/: bytes/g' mcquic/rans.pyi
          rm -rf stubs
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto update config schema and configs/README.md
