name: All tests

on:
  workflow_run:
    workflows: [Bump version]
    types:
      - completed
  workflow_dispatch:
    inputs: {}


jobs:
  test-install-on-posix:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        shell: [bash, zsh]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.9
      - name: Install and test mcquic
        shell: ${{ matrix.shell }}
        run: |
          ./install.sh
          eval "$(conda shell.bash hook)"

          conda activate mcquic

          if ! command -v mcquic &> /dev/null
          then
              exit 1
          fi
          mcquic -qp 3 assets/sample.png ./
          mcquic ./sample.mcq ./
          mcquic train --help
      - name: Test complete
        run: echo "All install test completed."
  test-install-on-windows:
    # The type of runner that the job will run on
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.9
      - name: Install mcquic
        run: |
          'y' | powershell -ExecutionPolicy ByPass -NoExit -noprofile -Command "& 'C:\Miniconda\condabin\conda-hook.ps1'; conda activate 'C:\Miniconda\'; './install.ps1'"
      - name: Test mcquic
        run: |
          C:\Miniconda\condabin\conda-hook.ps1
          conda activate 'C:\Miniconda\'
          conda activate mcquic
          mcquic -qp 3 assets/sample.png ./
          mcquic ./sample.mcq ./
          mcquic train --help
      - name: Test complete
        run: echo "All install test completed."
  test-conda-installation:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.9
      - name: Install mcquic
        run: |
          conda create -n mcquic python=3.9 pytorch torchvision cudatoolkit -c pytorch
          conda install -n mcquic mcquic -c xiaosu-zhu -c conda-forge
      - name: Test complete
        run: echo "All install test completed."
